### PR TITLE
add list.find

### PR DESCRIPTION
**Pull request by emmanueltouzery**
I found I needed List.find

### CODE REVIEW

**Comment by ulfryk** [comment]
Great idea and good job! 👍 

Add `typings` tests also…

…and maybe add `.find` to all other constructs -- Identity, Maybe, Either, Validation and especially `NEL` ?

**Comment by emmanueltouzery** [comment]
For Maybe for instance what would be the typescript signature you have in mind? I don't understand what you have in mind.

**Comment by ulfryk** [comment]
For `Maybe<T>` it would be `.find(fn: (val: T) => boolean): Maybe<T>`.

Ok :D I see that for `Maybe` it'll be just an alias for for `.filter` :)

But it makes sense in one point of view. You may have a method that accepts `Findable` and this method does not need to know what it takes, it just uses `.find` to get option of some value.

So it'll be nice to create internal interface:

```typescript
interface IFindable<T> {
  find(fn: (val: T) => boolean): Maybe<T>;
}
```

And implement it in all `monet` structures (that it can apply to).

**Comment by emmanueltouzery** [comment]
Rather than Findable, what about Traversable... We apply it to list and NEL only. Then we can potentially add later sort, groupBy, contains (the only issue is we'd like contains on Maybe too but we don't need an interface to have it in both spots), join (to make strings), dropWhile, takeWhile, zip, distinct. I have in my mind javaslang as a model:
http://static.javadoc.io/io.javaslang/javaslang/2.0.0/javaslang/collection/Traversable.html

My idea is that containers having multiple elements (today list, nel, maybe one day set, map) have a lot in common. Seems it's a shame to have a single purpose Findable interface instead of an interface tying these elements together?

Also it seems artificial to force 'find' on elements for which it doesn't feel natural like Either, no?

**Comment by emmanueltouzery** [comment]
Not saying i'd send PRs for all that though ;-) just suggesting a possible path.

**Comment by ulfryk** [comment]
What can I say. Java/Scala Traversable has powerful API that would be useful, but I don't think that extending `List` is worth our effort - there is a great lib that covers `List`, `Map`, `Set`, `OrderedMap`, `OrderedSet`, etc… for JS - [Immutable.js](https://facebook.github.io/immutable-js/docs/#/).

IMO it would be much better to create a port to extend `Immutable.js` with `monet` based sequences and operators (like `headMaybe`, `findMaybe`, etc.).

Anyway - we should add `.find` to  `List` and `NIL`.

…and forcing it on `Identity`, `Maybe`, `Either` and `Validation` may be not a best idea - I'll think about it for a while.

**Comment by emmanueltouzery** [comment]
Thanks for your thoughts. I actually depend on both monet & immutable.js in my little TS side-project. Immutable.js API does not quite work for me, but yes they have all the data structures.. Layering on top of them could make lots of sense.

Anyway for now added NEL support (no interface for now -- can add it if you want) and the tests you requested.

**Comment by ulfryk** [comment]
Looks fine now :)

Probably there is a way to extend `Immutable` API (as there is one to extend monet to fit users own needs).

**Comment by ulfryk** [comment]
Oh - maybe you can adjust `README.md` (aprts about List and NEL) ?

**Comment by emmanueltouzery** [comment]
done!

**Pull request merged**
