### PR TITLE
Adding Either.ofLeft factory function in order to satisfy linters 

### PR DESCRIPTION
**Pull request by LukaszTheProgrammer**
For details see #105

### CODE REVIEW

**Comment by ulfryk** [comment]
Great you did this so fast :)

But…
1) please add PR against `develop` branch not `master
2) As `Validation` has similar lower case constructors (`Validation.success()` and `Validation.fail()`) to keep consistency please provide `Either.left()` and `Either.right()`
3) Similar issue will occur with a `Maybe` so it would be nice if this PR introduced also `Maybe.some()` and `Maybe.none()`
4) Add typings and test them…
5) Update docs

**Comment by LukaszTheProgrammer** [comment]
@ulfryk 
As for 1. should I create my own feature branch from monets master or should I use feature/Either branch?

**Comment by ulfryk** [comment]
Create your own feature branch from `develop`

**Comment by LukaszTheProgrammer** [comment]
BTW.: have anyone ran typings tests recently? What I see from package.json is that 'npm test' compiles them but does not run them. I tried running them through ts-node and I got couple errors.
Some bindings like Nothing (Maybe.Nothing works)  or IO's ones are not working. Am I doing something wrong ? Is there any hidden setup ?

**Comment by ulfryk** [comment]
@LukaszTheProgrammer 
>  I see from package.json is that 'npm test' compiles them but does not run them

It should only try to compile them :) Real functionality tests are done in JS tests. TS test files are there only to check if code that is assumed to be properly typed can be compiled :)

So if `npm test` runs without errors - everything is OK.

**Comment by LukaszTheProgrammer** [comment]
What about a case like in maybe-spec.ts where there is a call to Nothing  like this:
`Nothing<string>().orJust('SURNAME');`

The binding exists but there is no Nothing defined on the root in monet.js thus leading this to fail in runtime.  I think either the binding should be removed or the factory method should be added.

**Comment by ulfryk** [comment]
You are right:

https://github.com/cwmyers/monet.js/blob/develop/src/monet.js#L579

And this is a bug, looks like factory method should be added…

**Comment by LukaszTheProgrammer** [comment]
I can do that in the comming extension for Either and Maybe. 
The question is whether you want it to be done as a separate branch ( due to some issue tracking ) or I can provide a fix here?

**Comment by ulfryk** [comment]
Feel free to provide it here :)

**Pull request closed without merging**
