### PR TITLE
Add .equals method for container-like monads

### PR DESCRIPTION
**Pull request by WojciechP**
Hi,
this PR adds a possibility to compare monadic values using `a.equals(b)` method. I assumed the following:
 * the `.equals` method is provided only for wrapper-like monads; it would make no sense on `Reader` or `IO`.
 * if the wrapped values have `.equals` method, is is used to perform deep comparison; otherwise, the values are compared with `===`. This approach makes it possible to compare nested monads and provides a way for users to specify custom comparisons for their data types.
 * `List` and `NEL` with the same values are equal.

Cheers,
Wojtek

### CODE REVIEW

**Comment by ulfryk** [comment]
:+1:

**Comment by ulfryk** [comment]
@WojciechP please update TS definitions with `equals`

**Comment by WojciechP** [comment]
Hi @cwmyers , @ulfryk,
sorry for such a delay.
I rebased the change and added proper typings.

**Comment by WojciechP** [comment]
Closing in favor of #57, which targets `develop` instead of `master`.

**Pull request closed without merging**
