### PR TITLE
#105  adding either and maybe linter specific factory functions

### PR DESCRIPTION
**Pull request by LukaszTheProgrammer**

### CODE REVIEW

**Comment by ulfryk** [comment]
LGTM :+1:

Just please update docs.

**Comment by LukaszTheProgrammer** [comment]
Done. Let me know if that's suitable.

**Comment by ulfryk** [comment]
I'll merge it soon to develop, and later when all docs are updated to more explicit version I'll publish next `alpha`

**Comment by LukaszTheProgrammer** [comment]
Thanks. Is there any way to be notified when the alpha will be released ?

**Comment by ulfryk** [comment]
Probably watching this repo would be enough :)

**Pull request merged**
