### PR TITLE
Add `fold` as alias of `cata` to `Maybe`, `Either`, and `Validation`

### PR DESCRIPTION
**Pull request by tbrisbane**
Part of #78 - New operators

Here I've added `fold` as an alias of `cata` to all of `Maybe`, `Either`, and `Validation`, and amended the relevant tests.

For `Maybe`, I've "overloaded" the existing `fold` method to forward to `cata` in the event that exactly 2 arguments are passed, but it'll do its usual curried implementation otherwise. I realise that this is a little awkward given that `Maybe#fold` now has two signatures (`fold<Z>(none: () => Z, some: (val: T) => Z): Z` and `fold<V>(val: V): (fn: (val: T) => V) => V`), however my aim was to keep things consistent with `fold` being an alias of `cata` in all cases. Feedback on this is welcome. :)

### CODE REVIEW

**Comment by ulfryk** [comment]
Hmm. I think overloading `Maybe#fold` is not a good idea… 

…in JavaScript…

…with static types.

**Comment by ulfryk** [comment]
I appreciate work already done. Code is consistent, tests and typings look, but I have to think abut it a bit more. I'm not sure if `.fold( => , => )` is great idea. It should by similar to `reduce` / `fold` on lists, but `Either` and `Validation` are somehow different. IMO to keep consistency we may try to meet in the middle -- `.fold((left: E) => z)((right: V) => Z)` ?

**Comment by tbrisbane** [comment]
Sorry for the radio silence on this!

I can definitely understand your hesitation around this - overloading in this manner isn't the most perfect of solutions, I agree.
It's a catch-22 situation: If we implement `Maybe#fold` as an alias of `Maybe#cata`, then we gain consistency in that all other `fold` implementations are aliases of `cata`, but then have to document two slightly different variations of `Maybe#fold`. On the other hand, if we leave `Maybe#fold` as it currently is, adding `fold` (as an alias of `cata`) to only `Either` and `Validation`, we lose consistency in that only some `fold`s will be aliases of `cata`; `Maybe#fold` won't be.

I see 3 possible options:
1. Overload `Maybe#fold` to add a version that is an alias of `cata` (as I did in this PR; keeps consistency but makes documentation odd)
2. Deprecate the current `Maybe#fold` and replace it with a new `fold` that is an alias of `cata` (a breaking change, but ultimately probably the nicest solution)
3. Break consistency by not having `Maybe#fold` as an alias of `cata`, and try to meet in the middle somewhere (although I would propose adding an *uncurried* `fold` to `Maybe` rather than *curried* `fold`s to `Either` and `Validation`)

Thoughts on moving forward? :)

**Comment by ulfryk** [comment]
Yeah, I'm still thinking about it. I'll consider 1 or 3 (I really don't like `2` as I personally use curried `Maybe#fold` a lot and I think it's really useful). Give me some more time please ;)

**Comment by tbrisbane** [comment]
No worries, my friend. No rush at all. :)

**Comment by ulfryk** [comment]
Ok. I've spent some time thinking about it and investigating similar patterns in Scala. First of all I completely agree that `fold` should be an alias for `cata` on Either and Validation. Secondly I think that this way it doesn't fit Maybe.

I've looked at Scala `Option` and `Either` and looked at `Traversable` as a good pattern for `fold`, `foldLeft` and `foldRight`.

Either and Validation have 2 sides and they completely different from List-like things, so there is now way to implement list-like `fold` - regular catamorphism seems to be the only way.

On the other hand Maybe is similar to a List - one element List (Some(e)) or Nil (None()). If we try to implement all `fold`, `foldLeft` and `foldRight` on it, they'll work exactly the same way. So I'd suggest slightly adjusting current implementation so it's similar to a `foldLeft`, from Scala docs:

```scala
def foldLeft[B](z: B)(op: (B, A) ⇒ B): B
```

In TypeScript it'll be:

```typescript
  fold<B>(acc: B)(op: (acc: B, value: A) => B): B
```

It is a breaking change - but easy to implement.

---

We can't implement Scala `Option`s `fold` as it's ( :( ) :
```scala
  def fold[B](ifEmpty: ⇒ B)(f: (A) ⇒ B): B
```

---

The other option i see is to leave Maybe `fold` as is and add `foldLeft` and `foldRight` identical to these in scala Option (same as in Traversable).

WDYT @tbrisbane (fyi @cwmyers )

**Comment by tbrisbane** [comment]
Following on from Scala is a decent approach here, I agree. :) Having said that, I think I prefer the approach of adding `foldLeft` and `foldRight` as separate methods, as this gives clients the freedom to choose the version of `fold` they wish to use.

If this is acceptable to you, I can amend the PR to add these methods. :)

---

On the notion of Scala's `Option#fold`:
> We can't implement Scala `Option`s `fold` as it's:
> `def fold[B](ifEmpty: ⇒ B)(f: (A) ⇒ B): B`

I think you alluded to this in the comments on #78, and I've thought about it, but I honestly can't see a situation where `fold[B](ifEmpty: ⇒ B)(f: (A) ⇒ B): B` (or its *un-curried* version, `fold[B](ifEmpty: ⇒ B, f: (A) ⇒ B): B`) would cause problems in JS... `Maybe#cata` already does exactly this?
I must be missing something. Can you provide a practical example of the issue you're alluding to? :)

**Comment by ulfryk** [comment]
> I think I prefer the approach of adding foldLeft and foldRight as separate methods, as this gives clients the freedom to choose the version of fold they wish to use.

:+1:

So I think the final version could be:
- leave `fold` on `Maybe` as it was (anyone can use `.cata`) as it's special structure
- if you find it very useful - keep overloaded `fold` - alias for `cata` on Maybe (but I find it a bit confusing)
- add `foldLeft` (and `foldRight` as alias) to `Maybe`
- add `fold` as alias of `cata` to `Either` and `Validation`

Is that ok for you @tbrisbane ?

---

In Scala `(ifEmpty: ⇒ B)` accepts variable of type `B` or function that returns `B`. And now think about situation where `B` is a function, e.g. `type B = (e: Event) => void`. JS is not capable of understanding type of passed function so in this case we have to separate methods not overload them :|

That's why I proposed separate lazy versions of `.orElse` and `.orSome` in #78

**Comment by tbrisbane** [comment]
Sounds good! I should be able to finalise the PR this coming weekend.

In regards to the `fold` alias: I'll have a think about it over the next day or two, as I'm still undecided.

On one hand, keeping the overload maintains consistency with the other `fold`s being aliases of `cata`, and even though JS cannot replicate Scala's "value, or a function returning a value" semantics, it makes more sense to me to opt for a function, given that a function returning a value is much more flexible than just a value (so the type would be strictly `ifEmpty: () ⇒ B`, and _not_ `ifEmpty: ⇒ B` in that case).
On the other hand, overloading `fold` in this way (i.e. not just providing an uncurried version, but an uncurried version with a _different type_ for the first parameter) feels iffy to me, and I can also see what you're saying in regards to `Maybe` being a bit more like a list...

Anyway, I'll aim to have something for you this weekend. :)

**Comment by ulfryk** [comment]
Ohh just one more thing. `foldLeft` and `foldRight` in Scala's Option have different signatures - they are _symmetric_ (so one can not be alias of another):

```scala
def foldLeft[B](z: B)(op: (B, A) ⇒ B): B
def foldRight[B](z: B)(op: (A, B) ⇒ B): B
```

`(B, A)` vs `(A, B)`

And its exactly how both these methods are implemented in Monet's List. So let's stick to it.

And about `Maybe`s fold, I believe it's important to keep backward compatibility here…

**Comment by tbrisbane** [comment]
I've finally had the time to sit down and update this. Boy, the Christmas period sure can be tiring!

I've removed the overloading of `fold` on `Maybe`, and added `foldLeft` and `foldRight` implementations to `Maybe`, `Either`, and `Validation` (`Either` and `Validation` are right-biased anyway, so this makes sense).

Please let me know of any necessary changes, and I should be able to carry them out without quite as much delay this time, haha. :)

I must note though that it does look at bit strange now that I see the current `Maybe#fold` alongside `Maybe#foldLeft` and `Maybe#foldRight`, but this is a consequence of preserving backwards compatibility. If ever you make a breaking release, I'd recommend updating `Maybe#fold` to be an alias of `Maybe#cata`. :)

**Comment by ulfryk** [comment]
> If ever you make a breaking release, I'd recommend updating `Maybe#fold` to be an alias of `Maybe#cata`.

For sure. Probably on `1.0.0` ;)

**Comment by ulfryk** [comment]
@tbrisbane there is still one thing to be done - please update `README.md` with added functionality ;)

**Comment by ulfryk** [comment]
@tbrisbane I'm working now on upgrading documentation so you can ignore my previous request. Just please rebase and run build and this change can be merged :)

**Comment by tbrisbane** [comment]
Oh ok, I literally just finished writing it and was about to commit hahaha. Did you still want what I've done? I might rebase and build, then post a patch for my doc changes here and you can apply it manually if you like. :)

**Comment by ulfryk** [comment]
If you have done it push it here too :)

**Comment by tbrisbane** [comment]
Alright, I've rebased and sorted the merge conflicts (there were a few that popped up from the addition of `contains`, etc). I've included my doc changes as well. :)

**Comment by ulfryk** [comment]
Great job @tbrisbane now I merge it and after #97 and one more (huge docs update) are merged I'll release another Alpha so new things can be tested in the wild :)

**Pull request merged**
